apiVersion: v2
name: kwakeup
description: >
  Helm chart for kwakeup — a cloud resource scheduler that starts and stops EC2 instances, RDS clusters, Kubernetes workloads, and more on a schedule.

type: application
version: 1.0.11
appVersion: "v1.0.8"
keywords:
  - cloud
  - scheduler
  - cost-saving
  - aws
  - gcp
  - azure
  - kubernetes
home: https://kwakeup.net
sources:
  - https://github.com/kwake-up/kwakeup-helm
maintainers:
  - name: kwakeup
    email: support@kwakeup.net
